name: Daily Commit

on:
  schedule:
    - cron: '2 17 * * *'  # Daily at 10:31 PM IST
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update Timestamp
        run: echo "// Last update: $(date -u)" > update.txt

      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add update.txt
          git commit -m "🕒 Daily Update: $(date -u)" || echo "No changes"
          git push
