name: Daily Commit

on:
  schedule:
    - cron: '1 10 * * *' # Every day at 3:25 PM IST (9:55 AM UTC)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update Date
        run: |
          echo "// Last updated: $(date -u)" > update.txt

      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.PAT }} # This is your PAT stored in GitHub Secrets
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add update.txt
          git commit -m "⏰ Daily Update: $(date -u)" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
